---
- name: Stop control plan server
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - etcd

- name: Create tempdir
  tempfile:
    state: directory
    suffix: backup_etcd
  register: backup_etcd_tempdir

- name: Import etcd backup file
  copy:
    src: "{{ restoration_snapshot_file }}"
    dest: "{{ backup_etcd_tempdir.path }}/snapshot-etcd.db"

- name: Delete previous etcd data
  file:
    path: "{{ agorakube_base_components.etcd.data_path }}"
    state: absent

- name: Render Restoration script
  template:
    src: restore.sh.j2
    dest: "{{ backup_etcd_tempdir.path }}/restore.sh"
    mode: u+rwx

- name: Restore ETCD data from backup file with rendered script
  shell: |
    {{ backup_etcd_tempdir.path }}/restore.sh
  when: restoration_snapshot_file is defined

- name: delete tmp file
  file:
    path: "{{ backup_etcd_tempdir.path }}"
    state: absent

- name: create folder {{ agorakube_base_components.etcd.data_path }}
  file:
    path: "{{ agorakube_base_components.etcd.data_path }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0700'

- name: Start control plan service
  systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager
    - etcd
