# -*- mode: ruby -*-
# vi: set ft=ruby :

$vagrant_box = "bento/ubuntu-18.04"
#$vagrant_box = "centos/7"

Vagrant.configure("2") do |config|
  # Node1 Block START
  #config.vm.define "node1" do |node1|
  #    node1.vm.box = $vagrant_box
  #    node1.vm.network "private_network", ip: "10.0.0.11"
  #    node1.vm.hostname = "node1"
  #    node1.vm.provider "virtualbox" do |vb|
  #        vb.customize ["modifyvm", :id, "--memory", 048]
  #        vb.customize ["modifyvm", :id, "--name", "node1"] 
  #    end
  #end
  # Node1 Block END

  # Node2 Block START
  #config.vm.define "node2" do |node2|
  #    node2.vm.box = $vagrant_box
  #    node2.vm.network "private_network", ip: "10.0.0.12"
  #    node2.vm.hostname = "node2"
  #    node2.vm.provider "virtualbox" do |vb|
  #        vb.customize ["modifyvm", :id, "--memory", 2048]
  #        vb.customize ["modifyvm", :id, "--name", "node2"] 
  #    end
  #end
  # Node2 Block END

  config.vm.define "deploy" do |deploy|
      deploy.vm.box = $vagrant_box
      deploy.vm.network :private_network, ip: "10.0.0.10"
      deploy.vm.hostname = "deploy"
      deploy.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--memory", 4096]
          vb.customize ["modifyvm", :id, "--name", "deploy"] 
      end
      deploy.vm.provision :shell, path: 'scripts/init.sh'
  end


  config.vm.synced_folder "../", "/agorakube"
  config.vm.synced_folder ".vagrant", "/vagrant/.vagrant"
end
