{
 "title": "Agorakube Dashboard : Logging (TEST VERSION)",
 "description": "From Loki Cheat Sheet.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "label_values({container_name=~\".+\"}, container_name)"
   },
   { "name": "job", "query": "label_values(job)" },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Log stream job : {job=\"$job\"}",
   "type": "table",
   "description": "{job=\"$job\"}",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"$job\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Total  Count of logs",
   "type": "singlestat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\", stream=~\"$stream\", pod_name=~\"$pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "singlestat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\", stream=~\"$stream\", pod_name=~\"$pod_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Count all the logs lines : count_over_time({job=\"fluent-bit\"}[5m])",
   "type": "graph",
   "description": "This query counts all the log lines within the last five minutes for the fluent-bit job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"fluent-bit\"}[5m])"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\", stream=~\"$stream\", pod_name=~\"$pod_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container_name=\"$container_name\", stream=~\"$stream\", pod_name=~\"$pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Rate : rate(({job=\"fluent-bit\"} |= \"error\" != \"timeout\")[10m])",
   "type": "stat",
   "description": "This query gets the per-second rate of all non-timeout errors within the last ten minutes for the fluent-bit job.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(({job=\"fluent-bit\"} |= \"error\" != \"timeout\")[10m])"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\", pod_name=~\"$pod_name\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "Aggregate, count, and group",
   "type": "heatmap",
   "description": "Get the count of logs during the last five minutes, grouping by level.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"fluent-bit\"}[5m])) by (level)"
    }
   ]
  }
 ]
}