{
 "title": "Agorakube Dashboard : Logging (TEST VERSION)",
 "description": "From Loki Cheat Sheet.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Service",
    "query": "label_values({container_name=~\".+\"}, container_name)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values({container_name=\"$container_name\"}, pod_name)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({container_name=\"$container_name\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Log stream kubeproxy : {job=\"kubeproxy\"}",
   "type": "table",
   "description": "{job=\"kubeproxy\"}",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"kubeproxy\"}"
    }
   ]
  },
  {
   "title": "Log stream kubelet : {job=\"kubelet\"}",
   "type": "table",
   "description": "{job=\"kubelet\"}",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"kubelet\"}"
    }
   ]
  },
  {
   "title": "Log stream kube-scheduler : {job=\"kube-scheduler\"}",
   "type": "table",
   "description": "{job=\"kube-scheduler\"}",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"kube-scheduler\"}"
    }
   ]
  },
  {
   "title": "Log stream kube--controller-manager : {job=\"kube-controller-manager\"}",
   "type": "table",
   "description": "{job=\"kube-controller-manager\"}",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"kube-controller-manager\"}"
    }
   ]
  },
  {
   "title": "Log stream kube-apiserver : {job=\"kube-apiserver\"}",
   "type": "table",
   "description": "{job=\"kube-apiserver\"}",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"kube-apiserver\"}"
    }
   ]
  },
  {
   "title": "Total  Count of logs",
   "type": "singlestat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 40 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\", stream=~\"$stream\", pod_name=~\"$pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "singlestat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 40 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\", stream=~\"$stream\", pod_name=~\"$pod_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Count all the logs lines : count_over_time({job=\"fluent-bit\"}[5m])",
   "type": "graph",
   "description": "This query counts all the log lines within the last five minutes for the fluent-bit job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"fluent-bit\"}[5m])"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\", stream=~\"$stream\", pod_name=~\"$pod_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container_name=\"$container_name\", stream=~\"$stream\", pod_name=~\"$pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Rate : rate(({job=\"fluent-bit\"} |= \"error\" != \"timeout\")[10m])",
   "type": "stat",
   "description": "This query gets the per-second rate of all non-timeout errors within the last ten minutes for the fluent-bit job.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(({job=\"fluent-bit\"} |= \"error\" != \"timeout\")[10m])"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=\"$container_name\", pod_name=~\"$pod_name\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "Aggregate, count, and group",
   "type": "heatmap",
   "description": "Get the count of logs during the last five minutes, grouping by level.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"fluent-bit\"}[5m])) by (level)"
    }
   ]
  }
 ]
}